version: '3'

services:

  api-service:
    build:
      context: ./../api-service
      dockerfile: ./../api-service/Dockerfile.dev
    restart: always
    ports:
      - "9990:80"
    deploy:
      mode: replicated
      replicas: 1

  rabbitmq:
    # image: 'rabbitmq:3.9-alpine'
    image: 'rabbitmq:3.9-management'
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/
